name: Build SAPA APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Ambil kode SAPA
        uses: actions/checkout@v4

      - name: Siapkan Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Siapkan Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.9'

      - name: Build APK SAPA
        run: gradle assembleDebug

      - name: Simpan APK SAPA
        uses: actions/upload-artifact@v4
        with:
          name: SAPA-APK
          path: app/build/outputs/apk/debug/app-debug.apk
